### ISSUE TITLE
Why GP app not aviliable in my country?

### ISSUE THREAD

**Issue by LionZXY** [ulternate/nearby-chat#1]
I want try your app in Russia, but i can't do it. Why?

**Comment by ulternate** [comment]
I made this app as an experiment and was just testing it around with friends. 

I've released it and opened it up to other countries, it should be available in the Play store soon.

I don't image I'll update it much though, feel free to fork this repo and play around with it, or install the app from the store at this link: https://play.google.com/store/apps/details?id=com.danielcswain.nearbychat

Cheers
